name: !!str "Comanda manualÄƒ cu tipuri de date2"
on: !!str "workflow_dispatch"
jobs: !!map { 
  mesagerie: !!map { 
    runs-on: ubuntu-latest, 
    steps: !!seq [ 
             run: echo Salut cu tipuri de date2! 
           ] 
  } 
}

