name: Comanda manuală cu date de intrare
on: 
  workflow_dispatch:
    inputs:
      opțiunile_mele:
        description: 'Ce alegeți?'
        required:    true
        type:        choice
        options:
                     - 'unu'
                     - 'doi'
                     - 'trei'
jobs: 
  mesagerie: 
    runs-on: ubuntu-latest
    steps:
      - run: >
               echo Salut!
               Am optat pentru
               ${{inputs.opțiunile_mele}}.
