!!map {
     name: !!str "Comanda manualÄƒ cu tipuri de date45",
     on:   !!str "workflow_dispatch",
     jobs: !!map { 
             mesagerie: !!map { 
                          runs-on: !!str "ubuntu-latest", 
                          steps:   !!seq [ 
                                     run: !!str "echo Salut cu tipuri de date45!" 
                                   ] 
                        } 
           }
   }
