name: >-
        Comanda manuală 
        cu date de intrare
        și nume-de-rulare
run-name: Testarea opțiunii ${{ inputs.optiunile_mele }}
on: 
  workflow_dispatch:
    inputs:
      optiunile_mele:
        description: 'Ce alegeți?'
        required:    true
        type:        choice
        options:
                     - 'unu'
                     - 'doi'
                     - 'trei'
jobs: 
  mesagerie: 
    runs-on: ubuntu-latest
    steps:
      - run: >
               echo Salut!
               Am optat pentru
               ${{ inputs.optiunile_mele }}.
