name: Conținutul proiectului meu
on: 
  workflow_dispatch: !!null null
jobs: 
  informatiile: 
    runs-on: ubuntu-latest
    steps:
      - name: prepararea-proiectului (Git checkout)
        uses: actions/checkout@v5 
      - name: construcția-informației
        run:  |
               echo "Conținutul proiectului:"
               echo "`ls -la ${{ github.workspace }} | head -n 32`"

